const ASSETS = {
  PUBLIC: {
    TAG_LOGO: "/2025/badgelogo.webp",
    LOGO_RIM: "/2025/vertical_logo.webp",
    LOGO_RIM_WHITE: "/2025/logo-rim-white.webp",
    LOGO_BLACK: "/2025/logo.webp",
    LOGO_WHITE: "/2025/logo-white.webp",
    LOGO_COMBINED: "/2025/logo-combined.webp",
    NITTE_LOGO: "/2025/nitteLogoWhite.webp",
    GEARCLOCK: "/2025/GearClock.webp",
    EVENT_BG: "/2025/eventBg.webp",
    GAMER: "/2025/gamer.webp",
    RYOKO: "/2025/ryoko.webp",
  },
  PROFILE: {
    TROPHY: "/2025/profile/trophy.webp",
  },
  LOGIN: {
    BACKGROUND: "/2025/login/bg-login.webp",
    GEAR: "/2025/login/gear.webp",
  },
  LOADER: {
    SPACE_PORTAL_BG: "/2025/loader/space-portal-bg.webp",
    SPACE_PORTAL: "/2025/loader/space-portal.webp",
    EOELOGO: "/2025/loader/Echoes_Of_Eternity_Logo.webp",
    HOURGLASS: "/2025/loader/hourglass.webp",
  },
  AUDIO: {
    GEARCLOCK: "/2025/audio/GearClockAudio.mp3",
    GEARSOUND: "/2025/audio/gearsounds.mp3",
    TICK: "/2025/audio/tick.mp3",
    LEVEL2: "/2025/explore/audio/level2.mp3",
  },
  EXPLORE: {
    LOADING_BACKGROUND: "/2025/explore/loading_background.webp",
    LOADING_FOREGROUND: "/2025/explore/loading_foreground.webp",
    STONE: "/2025/explore/stone.webp",
  },
  PRONITE: {
    SHAAN: "/2025/pronites/shaan.webp",
    SCREENTOP: "/2025/pronites/screentop.webp",
    MASALACOFFEE: "/2025/pronites/masalacoffee.webp",
  },
  LEADERBOARD: {
    LEVEL1: "/2025/leaderboard/level1.png",
    LEVEL2: "/2025/leaderboard/level2.png",
    LEVEL3: "/2025/leaderboard/level3.png",
    LEVEL4: "/2025/leaderboard/level4.png",
    TIMESTONE: "/2025/leaderboard/timestone.png",
  },
  "3D": {
    BLUE_STONE: "/2025/explore/models/blue_stone.glb",
    MEDIEVAL_BOUNDED: "/2025/explore/models/medieval_bounded_final.glb",
    PORTAL: "/2025/explore/models/portal.glb",
    RYOKU: "/2025/explore/models/ryoku.glb",
    CLOCK: "/2025/gallery/3d/clock.glb",
    PENDULUM: "/2025/gallery/3d/pendulum.glb",
    DRUMS: "/2025/pronites/drums.glb",
    GUITARIST: "/2025/pronites/guitarist.glb",
    PIANIST: "/2025/pronites/pianist.glb",
    SHAAN: "/2025/pronites/shaan.glb",
    SINGER: "/2025/pronites/singer.glb",
    STAGE: "/2025/pronites/stage.glb",
    PROFILETAG: "/2025/profile/tag.glb",
  },
  ABOUT: {
    IMAGE1: "/2025/about/1.webp",
    IMAGE2: "/2025/about/2.webp",
    IMAGE3: "/2025/about/3.webp",
    IMAGE4: "/2025/about/4.webp",
    IMAGE5: "/2025/about/5.webp",
    IMAGE6: "/2025/about/6.webp",
    IMAGE7: "/2025/about/7.webp",
    IMAGE8: "/2025/about/8.webp",
  },
  GALLERY: {
    CAPTURELOGO: "/2025/gallery/capture-logo.webp",
    BACKGROUND: "/2025/gallery/galleryBg.webp",
    TABLET: "/2025/gallery/tablet.webp",
    THUMBNAIL18: "/2025/gallery/thumbnails/incridea18.webp",
    THUMBNAIL19: "/2025/gallery/thumbnails/incridea19.webp",
    THUMBNAIL20: "/2025/gallery/thumbnails/incridea20.webp",
    THUMBNAIL22: "/2025/gallery/thumbnails/incridea22.webp",
    THUMBNAIL23: "/2025/gallery/thumbnails/incridea23.webp",
    THUMBNAIL24: "/2025/gallery/thumbnails/incridea24.webp",
  },
  LANDING: {
    LOADERBG: "/2025/landing/loader/background.webp",
    LOADERCIRCLE: "/2025/landing/loader/circle.webp",
    BACKGROUND: "/2025/landing/background.webp",
    CLOCK: "/2025/landing/clock.webp",
    EOETEXT: "/2025/landing/eoelogo.webp",
    PILLAR: "/2025/landing/pillar.webp",
    OBJECT1: "/2025/landing/floatingObjects/1.webp",
    OBJECT2: "/2025/landing/floatingObjects/2.webp",
    OBJECT3: "/2025/landing/floatingObjects/3.webp",
    OBJECT4: "/2025/landing/floatingObjects/4.webp",
    OBJECT5: "/2025/landing/floatingObjects/5.webp",
    OBJECT6: "/2025/landing/floatingObjects/6.webp",
    OBJECT7: "/2025/landing/floatingObjects/7.webp",
  },
  TEAM: {
    ARYAN_SINGH: "/2025/team/aryan_singh.webp",
    ASHTON_MATHIAS: "/2025/team/ashton_mathias.webp",
    ATHUL_D_BHANDARY: "/2025/team/athul_d_bhandary.webp",
    CHAITRA: "/2025/team/chaitra.webp",
    GAURAV_DHANRAJA: "/2025/team/gaurav_dhanraja.webp",
    ISHAN: "/2025/team/ishan.webp",
    KARTHIK_SALIAN: "/2025/team/karthik_salian.webp",
    KARTHIK_P_K: "/2025/team/karthik_p_k.webp",
    KEERTHAN_K: "/2025/team/keerthan_k.webp",
    LEN_MENDONCA: "/2025/team/len_mendonca.webp",
    MUSTAFA: "/2025/team/mustafa.webp",
    NANDAN: "/2025/team/nandan.webp",
    OMKAR: "/2025/team/omkar.webp",
    PRAKASH_WADDAR: "/2025/team/prakash_waddar.webp",
    PRATHAM_A_KADEKAR: "/2025/team/pratham_a_kadekar.webp",
    RAHUL: "/2025/team/rahul.webp",
    RIYAZ_AHMED: "/2025/team/riyaz_ahmed.webp",
    SAMARTH: "/2025/team/samarth.webp",
    SATWIK_H: "/2025/team/satwik_h.webp",
    SATWIK_PRABHU: "/2025/team/satwik_prabhu.webp",
    SAYEEM_AHMED: "/2025/team/sayeem_ahmed.webp",
    SHISHIR: "/2025/team/shishir.webp",
    SNEHAL_SHETTY: "/2025/team/snehal_shetty.webp",
    SOURAV_BANGERA: '/2025/team/sourav_bangera.webp',
    VARSHITH: "/2025/team/varshith.webp",
  },
};

export { ASSETS };
